version: "3"

services:
  chrome:
    image: yukinying/chrome-headless-browser:latest
    container_name: chrome
#    volumes:
#      - "chrome-data:/var/"
    shm_size: 1g
    cap_add:
      - SYS_ADMIN
    networks:
      - back-tier
    expose:
      - "9222:9222"
#
#  redis:
#    image: redis
#    container_name: redis:letest
##    volumes:
##      - "chrome-data:/var/"
#    networks:
#      - back-tier
#
#  redis:
#    image:  ch
#    container_name: redis:letest
##    volumes:
##      - "chrome-data:/var/"
#    networks:
#      - back-tier
##
##volumes:
##  db-data:

networks:
  front-tier:
  back-tier: