version: "3"

services:
  chrome:
    image: yukinying/chrome-headless-browser:latest
    container_name: chrome
#    volumes:
#      - "chrome-data:/var/"
    shm_size: 1g
    cap_add:
      - SYS_ADMIN
    networks:
      - back-tier
    # try to hide the scrollbars pushing this flag in the entrypoint command
    command: --no-scrollbars
    # still not sure about --no-sandbox
  node:
    build: ./docker/node/
    container_name: node
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app:cached
    networks:
      - back-tier
    command: bash -c "yarn && npm rebuild node-sass && npm start"
#    links:
#    - php
#    - node
#
#  redis:
#    image: redis
#    container_name: redis:letest
##    volumes:
##      - "chrome-data:/var/"
#    networks:
#      - back-tier
#
#  redis:
#    image:  ch
#    container_name: redis:letest
##    volumes:
##      - "chrome-data:/var/"
#    networks:
#      - back-tier
##
##volumes:
##  db-data:

networks:
  back-tier:
